-- MySQL Script generated by MySQL Workbench
-- Sun Jul  3 11:20:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema voto_electronico_int_comercial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema voto_electronico_int_comercial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voto_electronico_int_comercial` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `voto_electronico_int_comercial` ;

-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `NombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`),
  UNIQUE INDEX `Nombre_UNIQUE` (`NombrePais` ASC) VISIBLE,
  UNIQUE INDEX `idPais_UNIQUE` (`idPais` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `NombreProvincia` VARCHAR(45) NOT NULL,
  `idPais` INT NOT NULL,
  PRIMARY KEY (`idProvincia`),
  UNIQUE INDEX `idProvincia_UNIQUE` (`idProvincia` ASC) VISIBLE,
  INDEX `fk_pais_provincia` (`idPais` ASC) VISIBLE,
  CONSTRAINT `fk_pais_provincia`
    FOREIGN KEY (`idPais`)
    REFERENCES `voto_electronico_int_comercial`.`pais` (`idPais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `NombreCiudad` VARCHAR(45) NOT NULL,
  `idProvincia` INT NOT NULL,
  PRIMARY KEY (`idCiudad`),
  UNIQUE INDEX `idCiudad_UNIQUE` (`idCiudad` ASC) VISIBLE,
  INDEX `fk_ciudad_provincia` (`idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_provincia`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `voto_electronico_int_comercial`.`provincia` (`idProvincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`estado_votacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`estado_votacion` (
  `idestado_Votacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion_estado` BIT(1) NOT NULL,
  PRIMARY KEY (`idestado_Votacion`),
  UNIQUE INDEX `idestado_Votacion_UNIQUE` (`idestado_Votacion` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`formas_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`formas_pago` (
  `idformas_pago` INT NOT NULL AUTO_INCREMENT,
  `descripcion_forma de pago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idformas_pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `usuario_bajaLogica` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`tipo_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`tipo_factura` (
  `idtipo_factura` INT NOT NULL,
  `tipo_factura` VARCHAR(45) NOT NULL,
  `descripcion_tipoFactura` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_factura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`tipo_votacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`tipo_votacion` (
  `idTipo_votacion` INT NOT NULL AUTO_INCREMENT,
  `limite_participantes` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `nombre_votacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_votacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `cuit` VARCHAR(45) NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  `fecha_confeccion` VARCHAR(45) NOT NULL,
  `factura_bajaLogica` VARCHAR(45) NULL DEFAULT NULL,
  `formas_pago_idformas_pago` INT NOT NULL,
  `usuario_idusuario1` INT NOT NULL,
  `tipo_factura_idtipo_factura` INT NOT NULL,
  `factura_aprobadoOno` BIT NOT NULL,
  `tipo_votacion_idTipo_votacion` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_formas_pago1_idx` (`formas_pago_idformas_pago` ASC) VISIBLE,
  INDEX `fk_factura_usuario1_idx` (`usuario_idusuario1` ASC) VISIBLE,
  INDEX `fk_factura_tipo_factura1_idx` (`tipo_factura_idtipo_factura` ASC) VISIBLE,
  INDEX `fk_factura_tipo_votacion1_idx` (`tipo_votacion_idTipo_votacion` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_formas_pago1`
    FOREIGN KEY (`formas_pago_idformas_pago`)
    REFERENCES `voto_electronico_int_comercial`.`formas_pago` (`idformas_pago`),
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`usuario_idusuario1`)
    REFERENCES `voto_electronico_int_comercial`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_tipo_factura1`
    FOREIGN KEY (`tipo_factura_idtipo_factura`)
    REFERENCES `voto_electronico_int_comercial`.`tipo_factura` (`idtipo_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_tipo_votacion1`
    FOREIGN KEY (`tipo_votacion_idTipo_votacion`)
    REFERENCES `voto_electronico_int_comercial`.`tipo_votacion` (`idTipo_votacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `login_bajaLogica` DATE NULL DEFAULT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  UNIQUE INDEX `idLogin_UNIQUE` (`idLogin` ASC) VISIBLE,
  INDEX `fk_login_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_login_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `voto_electronico_int_comercial`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`votacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`votacion` (
  `idVotacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion_Votacion` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_cierre` DATE NOT NULL,
  `Resultado_idResultado` INT NOT NULL,
  `estado_Votacion_idestado_Votacion` INT NOT NULL,
  `login_idLogin` INT NOT NULL,
  `tipo_votacion_idTipo_votacion` INT NOT NULL,
  `llave_tipoVotacionPremium` BIT NULL,
  PRIMARY KEY (`idVotacion`),
  UNIQUE INDEX `idVotacion_UNIQUE` (`idVotacion` ASC) VISIBLE,
  INDEX `fk_Votacion_estado_Votacion1_idx` (`estado_Votacion_idestado_Votacion` ASC) VISIBLE,
  INDEX `fk_Votacion_Resultado1_idx` (`Resultado_idResultado` ASC) VISIBLE,
  INDEX `fk_votacion_login1_idx` (`login_idLogin` ASC) VISIBLE,
  INDEX `fk_votacion_tipo_votacion1_idx` (`tipo_votacion_idTipo_votacion` ASC) VISIBLE,
  CONSTRAINT `fk_Votacion_estado_Votacion1`
    FOREIGN KEY (`estado_Votacion_idestado_Votacion`)
    REFERENCES `voto_electronico_int_comercial`.`estado_votacion` (`idestado_Votacion`),
  CONSTRAINT `fk_votacion_login1`
    FOREIGN KEY (`login_idLogin`)
    REFERENCES `voto_electronico_int_comercial`.`login` (`idLogin`),
  CONSTRAINT `fk_votacion_tipo_votacion1`
    FOREIGN KEY (`tipo_votacion_idTipo_votacion`)
    REFERENCES `voto_electronico_int_comercial`.`tipo_votacion` (`idTipo_votacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`opcion_votacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`opcion_votacion` (
  `idopcion_Votacion` INT NOT NULL AUTO_INCREMENT,
  `Votacion_idVotacion` INT NOT NULL,
  `opcion_votacion` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idopcion_Votacion`),
  UNIQUE INDEX `idopcion_Votacion_UNIQUE` (`idopcion_Votacion` ASC) VISIBLE,
  INDEX `fk_opcion_Votacion_Votacion1_idx` (`Votacion_idVotacion` ASC) VISIBLE,
  CONSTRAINT `fk_opcion_Votacion_Votacion1`
    FOREIGN KEY (`Votacion_idVotacion`)
    REFERENCES `voto_electronico_int_comercial`.`votacion` (`idVotacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`producto_llave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`producto_llave` (
  `idProducto_llave` INT NOT NULL,
  `fechaDeUso` VARCHAR(45) NOT NULL,
  `utilizadaONo` BIT(1) NOT NULL DEFAULT b'0',
  `producto_llavecol` VARCHAR(45) NULL DEFAULT NULL,
  `Factura_idFactura` INT NOT NULL,
  `tipo_votacion_idTipo_votacion` INT NOT NULL,
  `login_idLogin` INT NOT NULL,
  `codigo_key` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducto_llave`),
  INDEX `fk_producto_llave_Factura1_idx` (`Factura_idFactura` ASC) VISIBLE,
  INDEX `fk_producto_llave_tipo_votacion1_idx` (`tipo_votacion_idTipo_votacion` ASC) VISIBLE,
  INDEX `fk_producto_llave_login1_idx` (`login_idLogin` ASC) VISIBLE,
  UNIQUE INDEX `codigo_key_UNIQUE` (`codigo_key` ASC) VISIBLE,
  CONSTRAINT `fk_producto_llave_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `voto_electronico_int_comercial`.`factura` (`idFactura`),
  CONSTRAINT `fk_producto_llave_tipo_votacion1`
    FOREIGN KEY (`tipo_votacion_idTipo_votacion`)
    REFERENCES `voto_electronico_int_comercial`.`tipo_votacion` (`idTipo_votacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_llave_login1`
    FOREIGN KEY (`login_idLogin`)
    REFERENCES `voto_electronico_int_comercial`.`login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`resultado` (
  `idResultado` INT NOT NULL AUTO_INCREMENT,
  `descripcion_Resultado` VARCHAR(45) NOT NULL,
  `votacion_idVotacion` INT NOT NULL,
  PRIMARY KEY (`idResultado`),
  UNIQUE INDEX `idResultado_UNIQUE` (`idResultado` ASC) VISIBLE,
  INDEX `fk_resultado_votacion1_idx` (`votacion_idVotacion` ASC) VISIBLE,
  CONSTRAINT `fk_resultado_votacion1`
    FOREIGN KEY (`votacion_idVotacion`)
    REFERENCES `voto_electronico_int_comercial`.`votacion` (`idVotacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`ubicacion` (
  `idUbicacion` INT NOT NULL AUTO_INCREMENT,
  `idCiudad` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idUbicacion`),
  UNIQUE INDEX `idUbicacion_UNIQUE` (`idUbicacion` ASC) VISIBLE,
  INDEX `fk_ubicacion_usuario` (`idusuario` ASC) VISIBLE,
  INDEX `fk_Ubicacion_ciudad` (`idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_Ubicacion_ciudad`
    FOREIGN KEY (`idCiudad`)
    REFERENCES `voto_electronico_int_comercial`.`ciudad` (`idCiudad`),
  CONSTRAINT `fk_ubicacion_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `voto_electronico_int_comercial`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`voto` (
  `idDesc_Voto` INT NOT NULL AUTO_INCREMENT,
  `votoRealizado` BIT(1) NOT NULL,
  `fecha_voto` DATE NOT NULL,
  `opcion_Votacion_idopcion_Votacion` INT NOT NULL,
  PRIMARY KEY (`idDesc_Voto`),
  UNIQUE INDEX `idDesc_Voto_UNIQUE` (`idDesc_Voto` ASC) VISIBLE,
  INDEX `fk_desc_Voto_opcion_Votacion1_idx` (`opcion_Votacion_idopcion_Votacion` ASC) VISIBLE,
  CONSTRAINT `fk_desc_Voto_opcion_Votacion1`
    FOREIGN KEY (`opcion_Votacion_idopcion_Votacion`)
    REFERENCES `voto_electronico_int_comercial`.`opcion_votacion` (`idopcion_Votacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `voto_electronico_int_comercial`.`votante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voto_electronico_int_comercial`.`votante` (
  `idgrupo_Votacion` INT NOT NULL AUTO_INCREMENT,
  `Votacion_idVotacion` INT NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `voto_idDesc_Voto` INT NOT NULL,
  PRIMARY KEY (`idgrupo_Votacion`),
  UNIQUE INDEX `idgrupo_Votacion_UNIQUE` (`idgrupo_Votacion` ASC) VISIBLE,
  INDEX `fk_grupo_Votacion_Votacion1_idx` (`Votacion_idVotacion` ASC) VISIBLE,
  INDEX `fk_votante_voto1_idx` (`voto_idDesc_Voto` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_Votacion_Votacion1`
    FOREIGN KEY (`Votacion_idVotacion`)
    REFERENCES `voto_electronico_int_comercial`.`votacion` (`idVotacion`),
  CONSTRAINT `fk_votante_voto1`
    FOREIGN KEY (`voto_idDesc_Voto`)
    REFERENCES `voto_electronico_int_comercial`.`voto` (`idDesc_Voto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
